name: simbuild
channels:
  - conda-forge
dependencies:
  - cudatoolkit-dev  # linux
  - make             # linux 
  - xorg-libx11      # linux
  - cxx-compiler
  - fftw
  - boost-cpp
  - cmake
  - libtiff
  - liblapack
  - openblas

