package:
  name: cudasirecon
  version: 1.0.0

source:
  path: ..

build:
  number: 2
  # NOTE: for mac, you should export CUDA_VERSION before running conda build
  # it will look for cudatoolkit installed at /Developer/NVIDIA/CUDA-${CUDA_VERSION}
  string: 'cu{{ environ.get('CUDA_VERSION') }}'
  script_env:
    - CUDA_VERSION
  
requirements:
  build:
    - conda # [linux]
    - cudatoolkit-dev=10.0 # [linux]
    - gcc_linux-64=5.4.0 # [linux]
    - gxx_linux-64=5.4.0 # [linux]
    - openblas
    - lapack
    - cmake
    - boost
    - xorg-libx11

  run:
    - cudatoolkit=10.0 # [linux]
    - openblas
    - lapack
    - boost
    - xorg-libx11

test:
  commands:
    - cudaSireconDriver --help
      
