package:
  name: cudasirecon
  version: 1.0.2

source:
  path: ..

build:
  number: 2
  # NOTE: for mac, you should export CUDA_VERSION before running conda build
  # it will look for cudatoolkit installed at /Developer/NVIDIA/CUDA-${CUDA_VERSION}
  string: 'cu{{ environ.get('CUDA_VERSION') }}'
  script_env:
    - CUDA_VERSION
  
requirements:
  build:
    - {{ compiler("cxx") }} # [win]
    - ninja # [win]
    # {% if environ.get('CUDA_VERSION') == '10.0' %}
    # - conda # [linux]
    # - cudatoolkit-dev=10.0 # [linux]
    # {% elif environ.get('CUDA_VERSION') == '9.2' %}
    # - conda # [linux]
    # - cudatoolkit-dev=9.2 # [linux]
    # {% endif %}
    - gcc_linux-64=5.4.0 # [linux]
    - gxx_linux-64=5.4.0 # [linux]
    - liblapack
    - cmake
    - boost-cpp # [not win]
    - xorg-libx11 # [not win]

  run:
    {% if environ.get('CUDA_VERSION') == '10.1' %}
    - cudatoolkit=10.1 # [not osx]
    {% elif environ.get('CUDA_VERSION') == '10.0' %}
    - cudatoolkit=10.0 # [not osx]
    {% elif environ.get('CUDA_VERSION') == '9.2' %}
    - cudatoolkit=9.2 # [linux]
    {% elif environ.get('CUDA_VERSION') == '9.0' %}
    - cudatoolkit=9.0 # [not osx]
    {% endif %}
    - liblapack
    - boost-cpp #[not win]
    - xorg-libx11 # [not win]

test:
  commands:
    - cudasirecon --help
    - makeotf -h # [not win]

about:
  home: https://github.com/scopetools/cudasirecon
  license: GPL-3.0  
  summary: 'CUDA-Accelerated 3-beam SIM reconstruction software'
  description: 'CUDA-Accelerated 3-beam SIM reconstruction software'