package:
  name: cudasirecon
  version: 1.0.0

source:
  path: ..

build:
  number: 1
  string: 'cu10.0'
  
requirements:
  build:
    - conda
    - cudatoolkit-dev=10.0
    - gcc_linux-64=5.4.0 # [linux]
    - gxx_linux-64=5.4.0 # [linux]
    - openblas
    - lapack
    - cmake
    - boost
    - xorg-libx11

  run:
    - cudatoolkit=10.0
    - openblas
    - lapack
    - boost
    - xorg-libx11

test:
  commands:
      - cudaSireconDriver --help
      